version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    network_mode: "bridge"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongo_username}
      MONGO_INITDB_ROOT_PASSWORD: ${mongo_password}
    ports:
      - "${mongo_port}:27017"
    volumes:
      - ${DOCKER_VOLUME}/mongodb:/data/db
    command: mongod --auth

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    network_mode: "bridge"
    ports:
      - ${mongo_express_port}:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${mongo_express_username}
      ME_CONFIG_BASICAUTH_PASSWORD: ${mongo_express_password}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${mongo_username}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${mongo_password}
    external_links:
      - mongodb:mongodb
    depends_on:
      - mongo
