version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    network_mode: "bridge"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DOCKER_VOLUME}/mysql/conf:/etc/mysql/conf.d
      - ${DOCKER_VOLUME}/mysql/logs:/logs
      - ${DOCKER_VOLUME}/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_password}
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    container_name: mysql-adminer
    restart: always
    network_mode: "bridge"
    ports:
      - "${MYSQL_ADMIN_PORT}:8080"
    links:
      - "mysql:db"