version: '2'
services:
  redis:
    image: redis:4.0.6
    container_name: redis
    restart: always
    network_mode: "bridge"
    command: redis-server --appendonly yes --requirepass ${redis_password}
    ports:
      - "${redis_port}:6379"
    volumes:
      - ${DOCKER_VOLUME}/redis/data:/data